export const BankingFacilitiesTemplate = [
  {
    company: "Simpro",
    bank: "Axis",
    od: 0,
    wcd: 0,
    buyerCredit: 0,
    packingCredit: 0,
    bg: 0,
    lc: 0,
    fxLimit: 0,
    cp: 0,
    termLoan: 0,
    ncd: 0,
    ecb: 0,
  },
];

export const viewData = [
  {
    company: "Simpro",
    bank: "Axis",
    sanction_od: 0,
    sanction_wcd: 20,
    sanction_buyerCredit: 0,
    sanction_packingCredit: 0,
    sanction_bg: 100,
    sanction_lc: 500,
    sanction_fxLimit: 40,
    sanction_cp: 0,
    sanction_termLoan: 0,
    sanction_ncd: 0,
    sanction_ecb: 50,
    utilisation_od: 0,
    utilisation_wcd: 0,
    utilisation_buyerCredit: 0,
    utilisation_packingCredit: 0,
    utilisation_bg: 20,
    utilisation_lc: 20,
    utilisation_fxLimit: 0,
    utilisation_cp: 0,
    utilisation_termLoan: 0,
    utilisation_ncd: 0,
    utilisation_ecb: 0,
  },
  {
    company: "Simpro2",
    bank: "HDFC",
    sanction_od: 0,
    sanction_wcd: 20,
    sanction_buyerCredit: 0,
    sanction_packingCredit: 0,
    sanction_bg: 40,
    sanction_lc: 40,
    sanction_fxLimit: 40,
    sanction_cp: 0,
    sanction_termLoan: 0,
    sanction_ncd: 0,
    sanction_ecb: 50,
    utilisation_od: 0,
    utilisation_wcd: 0,
    utilisation_buyerCredit: 0,
    utilisation_packingCredit: 0,
    utilisation_bg: 20,
    utilisation_lc: 20,
    utilisation_fxLimit: 0,
    utilisation_cp: 0,
    utilisation_termLoan: 0,
    utilisation_ncd: 0,
    utilisation_ecb: 0,
  }
]
